const supabaseUrl = 'https://dlbovctcjufiegzwrgei.supabase.co';
const supabaseKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsYm92Y3RjanVmaWVnendyZ2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTUxNzczMTYsImV4cCI6MjAzMDc1MzMxNn0.AEP7Gq_AS-1bD01kUAyXf9Pqc9rdyuhulCkNNAzNTo0';